# Site settings
title: powered by tea
description: >
  Random stuff (probably mostly code related)
twitter_username: martyngigg
github_username:  martyngigg
encoding: utf-8
timezone: Europe/London

# Output
permalink: none

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript","tables", "with_toc_data"]
highlighter: pygments
